# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_led_buttons/design_led_buttons.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_buttons || ORIG_REF_NAME==design_led_buttons}]

# IP: bd/design_led_buttons/ip/design_led_buttons_processing_system7_0_0/design_led_buttons_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_buttons_processing_system7_0_0 || ORIG_REF_NAME==design_led_buttons_processing_system7_0_0}]

# IP: bd/design_led_buttons/ip/design_led_buttons_axi_gpio_0_0/design_led_buttons_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_buttons_axi_gpio_0_0 || ORIG_REF_NAME==design_led_buttons_axi_gpio_0_0}]

# IP: bd/design_led_buttons/ip/design_led_buttons_axi_gpio_1_0/design_led_buttons_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_buttons_axi_gpio_1_0 || ORIG_REF_NAME==design_led_buttons_axi_gpio_1_0}]

# IP: bd/design_led_buttons/ip/design_led_buttons_ps7_0_axi_periph_0/design_led_buttons_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_buttons_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_led_buttons_ps7_0_axi_periph_0}]

# IP: bd/design_led_buttons/ip/design_led_buttons_rst_ps7_0_100M_0/design_led_buttons_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_buttons_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_led_buttons_rst_ps7_0_100M_0}]

# IP: bd/design_led_buttons/ip/design_led_buttons_xbar_0/design_led_buttons_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_buttons_xbar_0 || ORIG_REF_NAME==design_led_buttons_xbar_0}]

# IP: bd/design_led_buttons/ip/design_led_buttons_auto_pc_0/design_led_buttons_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_buttons_auto_pc_0 || ORIG_REF_NAME==design_led_buttons_auto_pc_0}]

# XDC: bd/design_led_buttons/design_led_buttons_ooc.xdc
