# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kab/Desktop/workspace/ZedBoard_GPIO_Buttons/ZedBoard_GPIO_Buttons.srcs/sources_1/bd/design_led_buttons/ip/design_led_buttons_rst_ps7_0_100M_0/design_led_buttons_rst_ps7_0_100M_0.xci
# IP: The module: 'design_led_buttons_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kab/Desktop/workspace/ZedBoard_GPIO_Buttons/ZedBoard_GPIO_Buttons.srcs/sources_1/bd/design_led_buttons/ip/design_led_buttons_rst_ps7_0_100M_0/design_led_buttons_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_led_buttons_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/kab/Desktop/workspace/ZedBoard_GPIO_Buttons/ZedBoard_GPIO_Buttons.srcs/sources_1/bd/design_led_buttons/ip/design_led_buttons_rst_ps7_0_100M_0/design_led_buttons_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_led_buttons_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/kab/Desktop/workspace/ZedBoard_GPIO_Buttons/ZedBoard_GPIO_Buttons.srcs/sources_1/bd/design_led_buttons/ip/design_led_buttons_rst_ps7_0_100M_0/design_led_buttons_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_led_buttons_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/kab/Desktop/workspace/ZedBoard_GPIO_Buttons/ZedBoard_GPIO_Buttons.srcs/sources_1/bd/design_led_buttons/ip/design_led_buttons_rst_ps7_0_100M_0/design_led_buttons_rst_ps7_0_100M_0.xci
# IP: The module: 'design_led_buttons_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kab/Desktop/workspace/ZedBoard_GPIO_Buttons/ZedBoard_GPIO_Buttons.srcs/sources_1/bd/design_led_buttons/ip/design_led_buttons_rst_ps7_0_100M_0/design_led_buttons_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_led_buttons_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/kab/Desktop/workspace/ZedBoard_GPIO_Buttons/ZedBoard_GPIO_Buttons.srcs/sources_1/bd/design_led_buttons/ip/design_led_buttons_rst_ps7_0_100M_0/design_led_buttons_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_led_buttons_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/kab/Desktop/workspace/ZedBoard_GPIO_Buttons/ZedBoard_GPIO_Buttons.srcs/sources_1/bd/design_led_buttons/ip/design_led_buttons_rst_ps7_0_100M_0/design_led_buttons_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_led_buttons_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
